project_id: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: "content/docs/en/**/*.mdx"
    translation: "content/docs/%two_letters_code%/**/%original_file_name%"
